language: php
php:
  - 7.2
os: linux
sudo: false
dist: trusty

before_script:
- make
- make install
- wget -O - https://poggit.pmmp.io/res/travisInstall.sh | bash -s - || true
- wget -O - https://poggit.pmmp.io/res/travisPluginTest.php | php -- unstaged

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/TheMix.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - TheMix TheMix ; else true ; fi"

notifications:
  email: false